### PR TITLE
fix: watcher ignores output and regeneration in loop

### LINKED ISSUE #185: Generator with watcher keeps regenerating if AsyncAPI file gets overwritten but contains the same data
Given you generate the `nodejs` template in the same directory where the AsyncAPI file is located the watcher will keep regenerate in an endless loop.

We could save the hash of the file/folder to see if any changes occurred before regenerating.

### PR DESCRIPTION
**Pull request by derberg**
**Description**

- watcher now watches explicitly the location of the template specified by the user. Before it was watching location where the template was installed in the generator global location
```
/.../.nvm/versions/node/v12.16.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/nodejs-ws-template/output/src/api/index.js was changed
```
- watcher now by default ignores output directory
- watcher supports flow when you trigger generation with watcher in the root of the template
- bump chokidar to latest

**Related issue(s)**
Fixes #185

### CODE REVIEW

File: cli.js [hunk 1]
```diff
@@ -78,14 +78,19 @@ xfs.mkdirp(program.output, async err => {
 
   // If we want to watch for changes do that
   if (program.watchTemplate) {
-    const watchDir = path.resolve(Generator.DEFAULT_TEMPLATES_DIR, template);
+    const watchDir = path.resolve(template);
+    // Template name is needed as it is not always a part of the cli commad
+    // There is a use case that you run generator from a root of the template with `./` path
+    const templateName = require(path.resolve(watchDir,'./package.json')).name;
```
Comment (fmvilas) [inline cli.js:84]: Not sure if the slash there will create problems on Windows. Just in case, you can do this:

```suggestion
    const templateName = require(path.resolve(watchDir,'package.json')).name;
```
